WorkshopAsp/Controllers/ActivityController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using WorkshopAsp.Models.DomainModel.Interfaces;
using WorkshopAsp.Models;

namespace WorkshopAsp.Controllers
{
    public class ActivityController : Controller
    {
        private IActivityRepository repository;

        public ActivityController(IActivityRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult List(int orderId)
        {
            ViewBag.orderId = orderId;
            return View(repository.Activities.Where(a => a.OrderId == orderId));
        }

        public IActionResult Create(int orderId)
        {
            ViewBag.orderId = orderId;
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(Activity activity)
        {
            if (ModelState.IsValid)
            {
                repository.Save(activity);
                TempData["message"] = $"Zapisano";
            }
            else
            {
                TempData["message"] = $"Wystąpił błąd";
            }

            return RedirectToAction("List", new { orderId = activity.OrderId });
        }
    }
}

WorkshopAsp/Controllers/CarController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WorkshopAsp.Models;
using WorkshopAsp.Models.DomainModel.Interfaces;
using WorkshopAsp.Models.ViewModels;

namespace WorkshopAsp.Controllers
{
    public class CarController : Controller
    {
        private ICarRepository repository;
        public CarController(ICarRepository repository)
        {
            this.repository = repository;
        }

        public ViewResult List(int ownerId, string ownerFullName)
        {
            var OwnerCars = new OwnerCarViewModel
            {
                OwnerId = ownerId,
                OwnerFullName = ownerFullName,
                Cars = repository.Cars.Where(o => o.OwnerId == ownerId)
            };
        
            return View(OwnerCars);
        }

        public IActionResult Create(int ownerId)
        {
           ViewBag.ownerId = ownerId;
           return View("Create");
        }

        [HttpPost]
        public IActionResult Create(Car car)
        {
            if (ModelState.IsValid)
            {
                repository.Save(car);
                TempData["message"] = $"Zapisano";
            }
            else
            {
                TempData["message"] = $"Wystąpił błąd";
            }
            return RedirectToAction("List", "Owner");
        }

        public ViewResult Edit(int carId) =>
            View(repository.Cars.FirstOrDefault(c => c.Id == carId));

        [HttpPost]
        public IActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                repository.Save(car);
                TempData["message"] = $"Zapisano";
            }
            else
            {
                TempData["message"] = $"Wystąpił błąd";
            }
            return RedirectToAction("List", "Owner");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            repository.Delete(id);
            return RedirectToAction("List", "Owner");
        }
    }
}

WorkshopAsp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WorkshopAsp.Models;
using WorkshopAsp.Models.DomainModel.Interfaces;

namespace WorkshopAsp.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        public OrderController(IOrderRepository repository)
        {
            this.repository = repository;
        }
        public IActionResult List(int carId)
        {
            ViewBag.carId = carId;
            return View(repository.Orders.Where(o => o.CarId == carId));
        }

        public IActionResult End(int orderId, int carId)
        {
            repository.End(orderId);
            return RedirectToAction("List", new { carId });
        }

        public IActionResult Create(int carId)
        {
            ViewBag.carId = carId;
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                repository.Begin(order);
                TempData["message"] = $"Zapisano";
            }
            else
            {
                TempData["message"] = $"Wystąpił błąd";
            }
            return RedirectToAction("List", new { carId = order.CarId});
        }
    }
}

WorkshopAsp/Controllers/PartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WorkshopAsp.Models;
using WorkshopAsp.Models.DomainModel.Interfaces;
using WorkshopAsp.Models.DomainModel.Repositories;

namespace WorkshopAsp.Controllers
{
    public class PartController : Controller
    {
        private IPartRepository repository;
        public PartController(IPartRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult List(int activityId)
        {
            ViewBag.ActivityId = activityId;
            return View(repository.Parts.Where(p => p.ActivityId == activityId));
        }

        public IActionResult Create(int activityId)
        {
            ViewBag.ActivityId = activityId;
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(Part part)
        {
            if (ModelState.IsValid)
            {
                repository.Save(part);
                TempData["message"] = $"Zapisano";
            }
            else
            {
                TempData["message"] = $"Wystąpił błąd";
            }

            return RedirectToAction("List", new { activityId = part.ActivityId });
        }
    }
}

WorkshopAsp/Views/Shared/PartialActivity.cshtml
@model Activity
<tr>
    <td>
        @Model.Name
    </td>

    <td>
        @Model.LaborPrice
    </td>

    <td class="text-center">
        <form asp-action="Delete" method="post">
            <input type="button" class="btn btn-info btn-sm" value="Użyte części" onclick="location.href='@Url.Action("List", "Part", new { activityId = Model.Id})'" />
        </form>
    </td>
</tr>

WorkshopAsp/Views/Shared/PartialCar.cshtml
@model Car
<tr>
    <td>
        @Model.Mark @Model.Model
    </td>
    <td>
        @Model.Registration
    </td>
    <td class="text-center">
        <form asp-action="Delete" method="post">
            <a asp-action="Edit" class="btn btn-sm btn-warning" asp-route-carId="@Model.Id">Edytuj</a>
            <input type="hidden" name="id" value="@Model.Id" />
            <button type="submit" class="btn btn-danger btn-sm">Usuń</button>
            <input type="button" class="btn btn-info btn-sm" value="Zlecenia" onclick="location.href='@Url.Action("List", "Order", new { carId = Model.Id})'" />
        </form>
    </td>
</tr>

WorkshopAsp/Views/Shared/PartialOrder.cshtml
@model Order
<tr style="background-color:ghostwhite">

  <tr>
    <td>
        @Model.Name
    </td>

    <td>
        @if (Model.EndDate == null)
        {<p> Nieskończone </p>}
        else
        {<a>Zakończone</a>}
    </td>

    <td>
        @Model.StartDate
    </td>

    <td>
        @if (Model.EndDate == null)
        {<a2> --- </a2>}
        else
        { @Model.EndDate}
    </td>

    <td class="text-center">
        <form asp-action="Delete" method="post">
            <a asp-action="End" class="btn btn-sm btn-warning" asp-route-orderId="@Model.Id" asp-route-carId="@Model.CarId">Zakończ</a>
            <input type="hidden" name="id" value="@Model.Id" />
            <!--<button type="submit" class="btn btn-danger btn-sm">Usuń</button>-->
            <input type="button" class="btn btn-info btn-sm" value="Aktywności w ramach zlecenia" onclick="location.href='@Url.Action("List", "Activity", new { orderId = Model.Id})'" />
        </form>
    </td>
</tr>

WorkshopAsp/Views/Shared/PartialOwner.cshtml
@model Owner
<tr>
    <td>
        @Model.Name @Model.Surname
    </td>
    <td>
        @Model.PhoneNumber
    </td>
    <td class="text-center">
        <form asp-action="Delete" method="post">
            <a asp-action="Edit" class="btn btn-sm btn-warning" asp-route-ownerId="@Model.Id">Edytuj</a>
            <input type="hidden" name="id" value="@Model.Id" />
            <button type="submit" class="btn btn-danger btn-sm">Usuń</button>
            <input type="button" class="btn btn-info btn-sm" value="Samochody" onclick="location.href='@Url.Action("List", "Car", new { ownerId = Model.Id, ownerFullName = $"{Model.Name} {Model.Surname}" })'" />
        </form>
    </td>
</tr>

WorkshopAsp/Views/Shared/PartialPart.cshtml
@model Part
<tr>
    <td>
        @Model.Name
    </td>

    <td>
        @Model.Price
    </td>
</tr>

WorkshopAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <title>Workshop</title>
</head>
<body style="background-color:darkgrey">
    <div class="navbar navbar-inverse bg-inverse" role="navigation">
        <a class="navbar-brand" href="#">Warsztat</a>
    </div>

    <!--<div id="categories" class="col-3">
        Put something useful here later
    </div>-->
    <div class="col-9">
        @RenderBody()
    </div>

</body>
</html>